services:
  database:
    container_name: art-portfolios-database
    image: mysql:8.0
    env_file:
      - .db.env
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
    ports:
      - "3306:3306"

  backend:
    container_name: art-portfolios-backend
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./backend:/backend
      - /tmp/app/mysqld:/run/mysqld
    ports:
      - "8000:8000"
    depends_on:
      - database