version: "3.9"
services:
  db:
    container_name: art-portfolios-database
    image: mysql:8.0
    env_file:
      - .db.env
    volumes:
      - dev-db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    container_name: art-portfolios-backend
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations core &&
             python manage.py makemigrations portfolio &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - dev-static-data:/vol/web
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: dev-art-portfolios-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - dev-static-data:/vol/static
      - ./frontend:/frontend
    ports:
      - "5173:5173"
    depends_on:
      - db
      - backend

  # npm:
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: npm-util.Dockerfile
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./frontend:/frontend


volumes:
  dev-static-data:
  dev-db-data: