# Generated by Django 4.1.2 on 2022-10-30 11:43

from django.db import migrations, models
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(max_length=512, null=True)),
                ('image', models.FileField(upload_to=portfolio.models.image_file_path)),
                ('type', models.IntegerField(choices=[(1, 'Drawing'), (2, 'Painting'), (3, 'Sculpture'), (4, 'Tatoo'), (5, 'Photo'), (6, 'Digital')])),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'portfolio_art',
            },
        ),
    ]
