# Generated by Django 4.1.2 on 2022-11-03 01:28

from django.db import migrations, models
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('image', models.ImageField(null=True, upload_to=portfolio.models.image_file_path)),
                ('type', models.IntegerField(choices=[(1, 'Drawing'), (2, 'Painting'), (3, 'Sculpture'), (4, 'Tatoo'), (5, 'Photo'), (6, 'Digital')])),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'portfolio_art',
            },
        ),
    ]
