# Generated by Django 4.1.2 on 2022-11-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('group', models.IntegerField(choices=[(1, 'Author'), (2, 'Color'), (3, 'Material'), (3, 'Generic')])),
            ],
            options={
                'db_table': 'portfolio_tag',
            },
        ),
        migrations.AddField(
            model_name='art',
            name='tags',
            field=models.ManyToManyField(db_table='portfolio_art_tag', to='portfolio.tag'),
        ),
    ]
