# Generated by Django 4.1.2 on 2022-12-13 03:42

from django.db import migrations, models
import portfolio.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_taggroup_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(null=True, upload_to=portfolio.models.image_file_path)),
                ('instagram', models.CharField(max_length=128)),
                ('deviant', models.CharField(max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
