# Generated by Django 4.1.2 on 2022-12-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='artists',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.artist'),
            preserve_default=False,
        ),
    ]
