# Generated by Django 4.1.2 on 2023-02-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_art_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('alive', models.BooleanField()),
                ('first_appearance', models.DateField()),
            ],
        ),
    ]
