# Generated by Django 4.1.2 on 2023-02-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='deviant',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
