# Generated by Django 4.1.2 on 2023-03-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_artist_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='characters',
            field=models.ManyToManyField(db_table='portfolio_art_character', to='portfolio.character'),
        ),
    ]
